parameters:
  pool: ''

jobs:
- job: Linux
  container: unoplatform/wasm-build:2.1

  pool:
    vmImage: 'ubuntu-latest'
  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget
    DOTNET_ROOT: $(Agent.ToolsDirectory)/dotnet
    EMSCRIPTEN_VERSION: 1.39.18

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '2.2.x'

  - task: nventiveCanaryUpdater@5
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries')
    inputs:
      solution: 'XamlControlsGallery.Windows/XamlControlsGallery.sln'
      usePrivateFeed: false
      useNuGetOrg: true
      mergeBranch: true
      branchToMerge: 'uno'
      nugetUpdaterVersion: '2.0.6'
      allowDowngrade: true
      packageAuthor: 'nventive'
      summaryFile: '$(Build.ArtifactStagingDirectory)/Canary.md'
      resultFile: '$(Build.ArtifactStagingDirectory)/update_result.json'
  
  - bash: |
      cd ~
      git clone --branch $(EMSCRIPTEN_VERSION) https://github.com/emscripten-core/emsdk
      cd emsdk
      ./emsdk install $(EMSCRIPTEN_VERSION)
      ./emsdk activate $(EMSCRIPTEN_VERSION)

    displayName: 'Setup Emscripten'

  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '2.1.x'

  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'
      updateAssemblyInfo: false

  - script: |
      source ~/emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" $(build.sourcesdirectory)/XamlControlsGallery.Wasm/XamlControlsGallery.Wasm.csproj /bl:$(build.artifactstagingdirectory)\build.binlog

    env:
      GITVERSION_INFORMATIONALVERSION: $(GITVERSION_INFORMATIONALVERSION)

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/XamlControlsGallery.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/XamlUIBasics-wasm/FullAOT
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false


  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: xaml-gallery-aot-drop
      ArtifactType: Container
