resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.5
    
jobs:

- template: .vsts-win-build.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'windows-2019'

- template: .vsts-linux-build.yml
  parameters:
    name: Linux
