jobs:

- template: .vsts-win-build.yml
  parameters:
    name: Windows
    pool:
      name: Default
      demands:
      - VisualStudio_Version -equals 15.9.6

- template: .vsts-linux-build.yml
  parameters:
    name: Linux
    pool:
      name: Default
      demands:
      - agent.os -equals Linux