parameters:
  pool: ''

jobs:
- job: Linux
  container: nv-bionic-wasm

  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    maxParallel: 1 # One build machine at the time of writing this
    matrix:
      FullAOT:
        RuntimeMode: FullAOT
        MixedModeBuild: False
      Mixed:
       RuntimeMode: Mixed
       MixedModeBuild: True

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true
  
  
  - bash: |
      sudo chmod -R 777 /emsdk
      cd /emsdk
      sudo ./emsdk activate sdk-1.38.28-64bit

    displayName: 'Setup Enscripten'

  - bash: |
      source /emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release /p:MixedModeBuild=$(MixedModeBuild) $(build.sourcesdirectory)/XamlControlsGallery.Wasm/XamlControlsGallery.Wasm.csproj /bl:$(build.artifactstagingdirectory)\build.binlog

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/XamlControlsGallery.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/XamlUIBasics-wasm/$(RuntimeMode)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false


  - task: PublishBuildArtifacts@1
    # https://developercommunity.visualstudio.com/content/problem/284991/public-vsts-previouw-cant-set-build-number-of-pr-b.html
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: xaml-gallery-aot-drop
      ArtifactType: Container
